# Generated by Django 6.0.3 on 2026-04-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0006_alter_ingredient_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_requirements', models.CharField(choices=[('None', 'None'), ('Halal', 'Halal'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], default='None', max_length=20)),
                ('allergies', models.ManyToManyField(blank=True, related_name='allergies', to='food.ingredient')),
                ('disliked_cuisines', models.ManyToManyField(blank=True, related_name='disliked_cuisines', to='food.cuisine')),
                ('disliked_ingredients', models.ManyToManyField(blank=True, related_name='disliked_ingredients', to='food.ingredient')),
                ('preferred_cuisines', models.ManyToManyField(blank=True, related_name='preffered_cuisines', to='food.cuisine')),
                ('preferred_ingredients', models.ManyToManyField(blank=True, related_name='preffered_ingredients', to='food.ingredient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
