# Generated by Django 6.0.3 on 2026-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_preference',
            name='dietary_requirements',
        ),
        migrations.AddField(
            model_name='user_preference',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='is_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='is_nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
