# Generated by Django 6.0.3 on 2026-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name_plural': 'Cuisines'},
        ),
    ]
