# Generated by Django 6.0.3 on 2026-04-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_cuisine_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_description', models.TextField(blank=True)),
                ('meal_price', models.FloatField()),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('meal_is_vegan', models.BooleanField(default=False)),
                ('meal_is_vegetarian', models.BooleanField(default=False)),
                ('meal_is_halal', models.BooleanField(default=False)),
                ('meal_is_gluten_free', models.BooleanField(default=False)),
                ('meal_is_nut_free', models.BooleanField(default=False)),
                ('meal_created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_location', models.CharField(max_length=8)),
                ('meal_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
                ('meal_cuisine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.cuisine')),
                ('meal_ingredients', models.ManyToManyField(related_name='meals', to='food.ingredient')),
            ],
        ),
    ]
