# Generated by Django 6.0.3 on 2026-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_ingredient_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
